version: '3.8'

services:
  db:
    image: mariadb:10.9
    env_file:
      - .env.docker
    ports:
      - '3306:3306'

  backend:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: yarn start
    ports:
      - '3005:3005'
    environment:
      NODE_ENV: development
    env_file:
      - .env.docker
    depends_on:
      - db
    links:
      - db
